# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e3708b78f05cac1f1c64b6363d349517e7976a9a755feed0724ec6afa80b34275cbc48a0fb8bd082a295e327f17b2816b9e0b7b4d9a79e53a687547d2716f1

test:
  secret_key_base: 0d1b9c86cb880a5d91f40da1eb1e1e6aa4abda4ef7c6df04769484c76d35a476d77e37bd7a61d7a0ac487784d0b72765f25f45871a3abe5d17c49cdd2b981d29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
